# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]
permissions:
  contents: read
  id-token: write  # Required for OIDC
jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Verify Python Installation
      run: python --version

    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::637423376610:role/GithubActionsUserRole
        aws-region: us-east-1


    - run: sam build --template-file /home/runner/work/HandsOn1/HandsOn1/github-actions-with-aws-sam/template.yaml
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-hello-world --s3-bucket awshandsononemz --capabilities CAPABILITY_IAM --region us-east-1
