name: Java CI with Gradle and CD

on:
  push:
    branches: [ "master", "develop", "feature/**", "release/**", "hotfix/**" ]
  pull_request:
    branches: [ "master", "develop", "feature/**", "release/**", "hotfix/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Permission Allowed
      run: git update-index --chmod=+x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Install zip
      run: sudo apt-get install -y zip

    - name: Package Lambda Function
      run: |
        mkdir -p build/deployment
        zip -j build/deployment/function.zip build/libs/*.jar

  deploy_dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Deploy to Development
      run: |
        aws lambda update-function-code --function-name my-function-dev --zip-file fileb://build/deployment/function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  deploy_qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Deploy to QA
      if: github.ref == 'refs/heads/release/**'
      run: |
        aws lambda update-function-code --function-name my-function-qa --zip-file fileb://build/deployment/function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

  deploy_prod:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      run: |
        aws lambda update-function-code --function-name my-function-prod --zip-file fileb://build/deployment/function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
